
const shops = [
  {
    name: "Le Quinze",
    picture: "media/leQuinze.jpg",
    style: "drinks",
    price_range: "€€",  //[15, 25]
    ratings: "★★★★",
    trajet: 3,
    description: "",
    paiement: "",
    coordonnees: "15 Rue du Surmelin Paris France",
    phone: "0143643856",
    urlItineraire: "",
    site: "",
  },
  {
    name: "Burger Lutèce",
    picture: "media/burgerLutece.jpg",
    style: "restaurant",
    price_range: "€€",
    ratings: "★★★★★",
    trajet: "3 min",
    description: "",
    paiement: "",
    coordonnees: "30 Rue du Surmelin Paris France",
    phone: "0665409730",
    urlItineraire: "",
    site: "",
  },
  {
    name: "Larson News",
    picture: "",
    style: "restaurant",
    price_range: "€",
    ratings: "★★★★",
    trajet: "6 min",
    description: "",
    paiement: "",
    coordonnees: "30 Rue du Surmelin Paris France",
    phone: "0140318485",
    urlItineraire: "",
    site: "",
  },
  {
    name: "Larson News",
    picture: "",
    style: "restaurant",
    price_range: "€",
    ratings: "★★★★",
    trajet: "6 min",
    description: "",
    paiement: "",
    coordonnees: "30 Rue du Surmelin Paris France",
    phone: "0140318485",
    urlItineraire: "",
    site: "",
  },
  {
    name: "Larson News",
    picture: "",
    style: "restaurant",
    price_range: "€",
    ratings: "★★★★",
    trajet: "6 min",
    description: "",
    paiement: "",
    coordonnees: "30 Rue du Surmelin Paris France",
    phone: "0140318485",
    urlItineraire: "",
    site: "",
  },
  {
    name: "Larson News",
    picture: "",
    style: "restaurant",
    price_range: "€",
    ratings: "★★★★",
    trajet: "6 min",
    description: "",
    paiement: "",
    coordonnees: "30 Rue du Surmelin Paris France",
    phone: "0140318485",
    urlItineraire: "",
    site: "",
  },
];


export default shops;

