// catégorie de restaurant:  restaurant, snacking, boire

const shops = [
  {
    name: "Le Quinze",
    picture: "media/leQuinze.jpg",
    style: ["boire", "restaurant"],
    price_range: "€€",
    ratings: "★★★★",
    trajet: 3,
    description: "",
    paiement: "",
    coordonnees: "15 Rue du Surmelin",
    phone: "0143643856",
    urlItineraire: "https://goo.gl/maps/W9Thjmk5157EctMj6",
    site: "",
    style: "Bar, Pub",
  },
  {
    name: "Burger Lutèce",
    picture: "media/burgerLutece.jpg",
    category: ["restaurant", "snacking"],
    price_range: "€€",
    ratings: "★★★★★",
    trajet: 3,
    description: "Fresh & Tasty",
    paiement: "",
    coordonnees: "30 Rue du Surmelin",
    phone: "0665409730",
    urlItineraire: "https://goo.gl/maps/KtQe67oYk3kpJ4Ef7",
    site: "https://www.burgerlutece.fr/",
    style: "Burger",
  },
  {
    name: "Larson News",
    picture: "",
    category: ["boire", "restaurant"],
    price_range: "€",
    ratings: "★★★★",
    trajet: 6,
    description: "",
    paiement: "",
    coordonnees: "90 Av. Gambetta",
    phone: "0140318485",
    urlItineraire: "https://goo.gl/maps/TGmizXCFgaGETFNk6",
    site: "",
    style: "",
  },
  {
    name: "Boulangerie Roux",
    picture: "",
    category: "snacking",
    price_range: "€",
    ratings: "★★★",
    trajet: 5, 
    description: "Boulangerie, fermée le mercredi",
    paiement: "",
    coordonnees: "12 rue Pelleport",
    phone: "0143615739",
    urlItineraire: "https://goo.gl/maps/9MLfHzWpLXJEjUbJ9",
    site: "",
    style: "",
  },
  {
    name: "Au Troquet de la place",
    picture: "",
    category: ["restaurant", "boire"],
    price_range: "€€",
    ratings: "★★★★",
    trajet: 7,
    description: "",
    paiement: "",
    coordonnees: "177 Av. Gambetta",
    phone: "0140305107",
    urlItineraire: "https://goo.gl/maps/nLcSdXP6vGjKabgR6",
    site: "",
    style: "",
  },
  {
    name: "Peppe Pizzeria",
    picture: "",
    category: ["restaurant", "snacking"],
    price_range: "€€",
    ratings: "★★★★★",
    trajet: 14,
    description: "",
    paiement: "",
    coordonnees: "2 Place Saint-Blaise",
    phone: "0145355913",
    urlItineraire: "https://goo.gl/maps/a1LvGU3XHvumXki67",
    site: "https://www.peppeparis.fr/",
    style: "Pizza",
  },
  {
    name: "Boulangerie Walter Camaj",
    picture: "",
    category: ["snacking"],
    price_range: "€",
    ratings: "★★★★",
    trajet: 5,
    description: "Boulangerie, fermée le mercredi",
    paiement: "",
    coordonnees: "177 avenue Gambetta",
    phone: "",
    urlItineraire: "https://goo.gl/maps/MipuZcRJAEQcwsvP6",
    site: "",
    style: "",
  },
  {
    name: "Boulangerie Meunier",
    picture: "",
    category: ["snacking"],
    price_range: "€",
    ratings: "★★★",
    trajet: 6,
    description: "Boulangerie, fermée le lundi",
    paiement: "",
    coordonnees: "10 rue du capitaine Ferber",
    phone: "",
    urlItineraire: "https://goo.gl/maps/sYu95cyZqEjxg8pA7",
    site: "",
    style: "",
  },
  {
    name: "Aux Petits Oignons",
    picture: "",
    category: ["restaurant", "boire"],
    price_range: "€€",
    ratings: "★★★★",
    trajet: 7,
    description: "Plats français modernes et originaux dans un intérieur chaleureux de type bistro de quartier, avec terrasse.",
    paiement: "",
    coordonnees: "11 rue Dupont de l'Eure",
    phone: "0143641886",
    urlItineraire: "https://goo.gl/maps/wyFXsG5Vi6bVvysDA",
    site: "auxpetitsoignonsparis.fr",
    style: "",
  },
  {
    name: "Bar de la place Edith Piaf",
    picture: "",
    category: ["boire", "restaurant"],
    price_range: "€",
    ratings: "★★★★",
    trajet: 6,
    description: "Bar de quartier",
    paiement: "",
    coordonnees: "22 Rue de la Py",
    phone: "0143610932",
    urlItineraire: "https://goo.gl/maps/p3quDncS778ZfpKn9",
    site: "",
    style: "",
  },
  {
    name: "La Gambette à Pain",
    picture: "",
    category: ["snacking"],
    price_range: "€€",
    ratings: "★★★★",
    trajet: 5,
    description: "Boulangerie, fermée le week-end",
    paiement: "",
    coordonnees: "86 Avenue Gambetta",
    phone: "0143645234",
    urlItineraire: "https://goo.gl/maps/4Bps7MRkLXMHcSXdA",
    site: "",
    style: "",
  },
  {
    name: "",
    picture: "",
    category: [""],
    price_range: "€€",
    ratings: "★★★★★",
    trajet: '',
    description: "",
    paiement: "",
    coordonnees: "",
    phone: "",
    urlItineraire: "",
    site: "",
    style: "",
  },
  {
    name: "",
    picture: "",
    category: [""],
    price_range: "€€",
    ratings: "★★★★★",
    trajet: '',
    description: "",
    paiement: "",
    coordonnees: "",
    phone: "",
    urlItineraire: "",
    site: "",
    style: "",
  },
  {
    name: "",
    picture: "",
    category: [""],
    price_range: "€€",
    ratings: "★★★★★",
    trajet: '',
    description: "",
    paiement: "",
    coordonnees: "",
    phone: "",
    urlItineraire: "",
    site: "",
    style: "",
  },
  {
    name: "",
    picture: "",
    category: [""],
    price_range: "€€",
    ratings: "★★★★★",
    trajet: '',
    description: "",
    paiement: "",
    coordonnees: "",
    phone: "",
    urlItineraire: "",
    site: "",
    style: "",
  },
  {
    name: "",
    picture: "",
    category: [""],
    price_range: "€€",
    ratings: "★★★★★",
    trajet: '',
    description: "",
    paiement: "",
    coordonnees: "",
    phone: "",
    urlItineraire: "",
    site: "",
    style: "",
  },
  {
    name: "",
    picture: "",
    category: [""],
    price_range: "€€",
    ratings: "★★★★★",
    trajet: '',
    description: "",
    paiement: "",
    coordonnees: "",
    phone: "",
    urlItineraire: "",
    site: "",
    style: "",
  },
];


export default shops;
category