// catégorie de restaurant:  restaurant, snacking, boire

const shops = [
  {
    name: "Le Quinze",
    picture: "media/leQuinze.jpg",
    style: ["boire", "restaurant"],
    price_range: "€€",
    ratings: "★★★★",
    trajet: 3,
    description: "",
    paiement: "",
    coordonnees: "15 Rue du Surmelin",
    phone: "0143643856",
    urlItineraire: "https://goo.gl/maps/W9Thjmk5157EctMj6",
    site: "",
  },
  {
    name: "Burger Lutèce",
    picture: "media/burgerLutece.jpg",
    style: ["restaurant", "snacking"],
    price_range: "€€",
    ratings: "★★★★★",
    trajet: 3,
    description: "Fresh & Tasty",
    paiement: "",
    coordonnees: "30 Rue du Surmelin",
    phone: "0665409730",
    urlItineraire: "https://goo.gl/maps/KtQe67oYk3kpJ4Ef7",
    site: "https://www.burgerlutece.fr/",
  },
  {
    name: "Larson News",
    picture: "",
    style: ["boire", "restaurant"],
    price_range: "€",
    ratings: "★★★★",
    trajet: 6,
    description: "",
    paiement: "",
    coordonnees: "90 Av. Gambetta",
    phone: "0140318485",
    urlItineraire: "https://goo.gl/maps/TGmizXCFgaGETFNk6",
    site: "",
  },
  {
    name: "Boulangerie Roux",
    picture: "",
    style: "snacking",
    price_range: "€",
    ratings: "★★★",
    trajet: 5, 
    description: "",
    paiement: "",
    coordonnees: "12 rue Pelleport",
    phone: "0143615739",
    urlItineraire: "https://goo.gl/maps/9MLfHzWpLXJEjUbJ9",
    site: "",
  },
  {
    name: "Au Troquet de la place",
    picture: "",
    style: ["restaurant", "boire"],
    price_range: "€€",
    ratings: "★★★★",
    trajet: "6 min",
    description: "",
    paiement: "",
    coordonnees: "177 Av. Gambetta",
    phone: "0140305107",
    urlItineraire: "https://goo.gl/maps/nLcSdXP6vGjKabgR6",
    site: "",
  },
  {
    name: "Peppe Pizzeria",
    picture: "",
    style: ["restaurant", "snacking"],
    price_range: "€€",
    ratings: "★★★★★",
    trajet: "6 min",
    description: "",
    paiement: "",
    coordonnees: "2 Place Saint-Blaise",
    phone: "0140318485",
    urlItineraire: "",
    site: "",
  },
];


export default shops;

